{
 "title": "JWT-PIZZA-DASHBOARD",
 "description": "main dashboard for jwt pizza deliverables",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "request_pizzaCreationTime{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "pizza creation"
    },
    {
     "expr": "request_serviceLatency{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "service endpoints"
    }
   ]
  },
  {
   "title": "Internal Usages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_cpuPercentage{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "request_memoryUsage{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "MEMORY"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_revenue{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "auth results per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_successes{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "successes"
    },
    {
     "expr": "rate(request_failures{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Pizza Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_pizzasSold{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "pizza sold per minute"
    },
    {
     "expr": "request_pizzaFailures{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "pizza creation failures"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_totalRequests{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(request_delRequests{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_getRequests{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_putRequests{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(request_postRequests{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "Users logged in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "request_activeUsers{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}